### PR TITLE
Allow printing into existing strings

### PR DESCRIPTION
**Pull request by Xiretza**
This adds a new syntax `sprintf!(=> &mut s, "%d", args...)` to allow printing into/appending to an existing string.

### CODE REVIEW

**Comment by ridiculousfish** [comment]
Thank you!

**Comment by mqudsi** [comment]
Note that this breaks existing `sprintf_locale()` usage, namely the `sprintf_loc!()` macro in fish's `src/builtins/printf.rs`.

**Comment by krobelus** [comment]
@mqudsi fixed by 81cdd51597f67e65dba7cb488ac88e1d8ed980d8

**Comment by mqudsi** [comment]
I was *just* about to push a fix myself!

```diff
commit c536ae4b6d40ff1eb900be8afa7b1e691ec474ad
Author: Mahmoud Al-Qudsi <mqudsi@neosmart.net>
Date:   Sat Apr 29 12:46:28 2023 -0500

    Pull in fish-shell/printf-compat#1
    
    This adds a new mode to the sprintf!() macro for appending into an existing
    string. See https://github.com/fish-shell/printf-compat/pull/1
    
    The merged PR unfortunately breaks existing sprintf_locale() usage (which has
    been changed to take a mutable target as the first parameter instead of
    returning a new WString).
    
    The usage site has been changed to preserve the old behavior, though it may now
    be possible to take advantage of the new append functionality instead of
    allocating a new WString each time the sprint_loc!() macro is called.

diff --git a/fish-rust/Cargo.lock b/fish-rust/Cargo.lock
index 786ee7097..00e5004bf 100644
--- a/fish-rust/Cargo.lock
+++ b/fish-rust/Cargo.lock
@@ -821,7 +821,7 @@ dependencies = [
 [[package]]
 name = "printf-compat"
 version = "0.1.1"
-source = "git+https://github.com/fish-shell/printf-compat.git?branch=fish#d5f98dc8ce7a63e6639b08082ffbc6499021260c"
+source = "git+https://github.com/fish-shell/printf-compat.git?branch=fish#ff460021ba11e2a2c69e1fe04cb1961d6a75be15"
 dependencies = [
  "bitflags",
  "itertools 0.9.0",
diff --git a/fish-rust/src/builtins/printf.rs b/fish-rust/src/builtins/printf.rs
index 7aa53ab00..a79f793db 100644
--- a/fish-rust/src/builtins/printf.rs
+++ b/fish-rust/src/builtins/printf.rs
@@ -265,13 +265,16 @@ impl<'a> builtin_printf_state_t<'a> {
             (
             $fmt:expr, // format string of type &wstr
             $($arg:expr),* // arguments
-            ) => {
+            ) => {{
+                let mut target = WString::new();
                 sprintf_locale(
+                    &mut target,
                     $fmt,
                     &self.locale,
                     &[$($arg.to_arg()),*]
-                )
-            }
+                );
+                target
+            }}
         }
 
         // Start with everything except the conversion specifier.
```

**Pull request merged**
